version: "3.8"
services:
  geth:
    build:
      context: ./geth
      dockerfile: Dockerfile.dev
    volumes:
      - geth-dev:/root/.ethereum
      - geth-dev:/usr/ethereum
    restart: unless-stopped
    ports:
      - 30303:30303
      - 8545:8545
      - 8546:8546
    stop_signal: SIGINT
    stop_grace_period: 2m
  eth-observer:
    build:
      context: .
      dockerfile: Dockerfile.dev
volumes:
  geth-dev:
