version: "3.8"
services:
  geth:
    build:
      context: ./geth
      dockerfile: Dockerfile.test
    ports:
      - 30303:30303
      - 8546:8546
    stop_signal: SIGINT
  eth-address-observer:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - HOST=geth:8546
    depends_on:
      - geth
