name: test-ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker build -t poonkt/eth-address-observer:latest -f Dockerfile.test .
      - name: Run tests
        run: docker run -t --rm poonkt/eth-address-observer:latest
